On Error Resume Next

Set objArgs = WScript.Arguments

excelPath = objArgs(0)
valorBusqueda = objArgs(1)

' === Parámetros ===
excelPath = "C:\ruta\al\archivo.xlsx"  ' Cambia esta ruta
hojaNombre = "tipoCambio"                   ' Nombre de la hoja
valorBusqueda = "test"                 ' Valor a buscar

' === Inicializa Excel ===
'Genera un objeto de tipo Excel Application
Set objExcel = CreateObject("Excel.Application")

'Parámetro para indicar si se quiere visible la aplicación de Excel
objExcel.Application.Visible = True
'Evita movimiento de pantalla
objExcel.Application.ScreenUpdating = True
'Parámetro evitar mostrar pop ups de Excel
objExcel.Application.DisplayAlerts = False

Set objWorkbook = objExcel.Workbooks.Open(excelPath)
Set objSheet = objWorkbook.Sheets(hojaNombre)

' === Buscar valor en la hoja ===
Set celda = objSheet.Cells.Find(valorBusqueda)

If Not celda Is Nothing Then
    fila = celda.Row
    If fila >= 1 Then
        objSheet.Range("A1:A" & fila).EntireRow.Delete
        WScript.Echo "Se eliminaron las filas de la 1 a la " & fila
    End If
Else
    WScript.Echo "Valor '" & valorBusqueda & "' no encontrado."
End If

' === Guardar y cerrar ===
objWorkbook.Save
objWorkbook.Close False
objExcel.Quit

'Devuelve el error en caso de
If Err.Number <> 0 Then
    ' Guardar y cerrar el libro de refacturación
    objWorkbook.Save
    objWorkbook.Close
    ' Cerrar la aplicación de Excel
    objExcel.Quit
    Msg = "Error was generated by " & Err.Source & ". " & Err.Description
    WScript.StdOut.WriteLine Msg
Else
    WScript.StdOut.WriteLine "Script executed successfully."
End if
