On Error Resume Next

Set objArgs = WScript.Arguments

fecha = objArgs(0)
valorDetermina = objArgs(1)
valorDOF = objArgs(2)
valorSolventa = objArgs(3)
WorkbookRefacturacion = objArgs(4)

'fecha = "09/07/2025"
'valorDetermina = 18.5733
'valorDOF = 18.7140
'valorSolventa = 18.6698
'WorkbookRefacturacion = "C:\Users\HE678HU\OneDrive - EY\.Repsol\Reporte Regulatorio\Timbrado\Refacturacion_regular_v2.xlsx"


'Genera un objeto de tipo Excel Application
Set objExcel = CreateObject("Excel.Application")

'Parámetro para indicar si se quiere visible la aplicación de Excel
objExcel.Application.Visible = False
'Evita movimiento de pantalla
objExcel.Application.ScreenUpdating = False
'Parámetro evitar mostrar pop ups de Excel
objExcel.Application.DisplayAlerts = False

WorkbookSheetRefacturacion = "TC"

'Abre libro Excel
Set objWorkbookPathRefacturacion = objExcel.Workbooks.Open(WorkbookRefacturacion, 0)
Set objWorkbookSheetRefacturacion = objWorkbookPathRefacturacion.Worksheets(WorkbookSheetRefacturacion)

existe = False
fila = 2

Do While objWorkbookSheetRefacturacion.Cells(fila, 1).Value <> ""
    If CStr(objWorkbookSheetRefacturacion.Cells(fila, 1).Value) = CStr(fecha) Then
        existe = True
        Exit Do
    End If
    fila = fila + 1
Loop

If Not existe Then
    objWorkbookSheetRefacturacion.Cells(fila, 1).Value = fecha
    objWorkbookSheetRefacturacion.Cells(fila, 2).Value = valorDetermina
    objWorkbookSheetRefacturacion.Cells(fila, 3).Value = valorDOF
    objWorkbookSheetRefacturacion.Cells(fila, 4).Value = valorSolventa
End If

' Guardar y cerrar el libro
objWorkbookPathRefacturacion.Save
objWorkbookPathRefacturacion.Close

objExcel.Quit

'Devuelve el error en caso de
If Err.Number <> 0 Then
    ' Cerrar la aplicación de Excel
    objExcel.Quit
    Msg = "Error was generated by " & Err.Source & ". " & Err.Description
    WScript.StdOut.WriteLine Msg
Else
    WScript.StdOut.WriteLine "Script executed successfully."
End if