On Error Resume Next

Set objArgs = WScript.Arguments

WorkbookPathRexmex = objArgs(0)
WorkbookPathRef = objArgs(1)
ActualMonth = objArgs(2)

'WorkbookPathRexmex = "C:\Users\se109874\OneDrive - Repsol\Documentos\Refacturacion\REXMEX - Cuenta Operativa 2025_120525.xlsx"
'WorkbookPathRef = "C:\Users\se109874\OneDrive - Repsol\Documentos\Refacturacion\Layout refacturación may-25.xlsx"
'ActualMonth = 3

WorkbookSheetRexmex = "Cuenta Operativa"
WorkbookSheetLayout = "Layout"

'Genera un objeto de tipo Excel Application
Set objExcel = CreateObject("Excel.Application")

'Parámetro para indicar si se quiere visible la aplicación de Excel
objExcel.Application.Visible = False
'Evita movimiento de pantalla
objExcel.Application.ScreenUpdating = False
'Parámetro evitar mostrar pop ups de Excel
objExcel.Application.DisplayAlerts = False

'Abre libro Excel
Set objWorkbookPathRef = objExcel.Workbooks.Open(WorkbookPathRef, 0)
Set objWorkbookSheetRefL = objWorkbookPathRef.Worksheets(WorkbookSheetLayout)
Set objWorkbookSheetRef = objWorkbookPathRef.Worksheets("BL29")

' --- Optimización de rendimiento: lectura y escritura por lotes ---
Dim wbsDict, wbsDictH, pepCounterDict
Set wbsDict     = CreateObject("Scripting.Dictionary")
Set wbsDictH    = CreateObject("Scripting.Dictionary")
Set pepCounterDict = CreateObject("Scripting.Dictionary")

Dim data, rowNum, totalRows
Dim wbsValue, agValue, sKey
Dim results()

lastRow = objWorkbookSheetRef.Cells(objWorkbookSheetRef.Rows.Count, 1).End(-4162).Row ' -4162 = xlUp

' Leer todas las filas a un array (más rápido que trabajar directo con Cells)
data = objWorkbookSheetRef.Range("A2:AV" & lastRow).Value ' A = col 1, AG = col 33
totalRows = UBound(data, 1)
ReDim results(totalRows) ' Guardar filas que se deben ocultar

For rowNum = 1 To totalRows ' Ya que empezamos en A2, este es índice 1
    wbsValue = Trim(data(rowNum, 3))     ' Columna C
    agValue  = Trim(data(rowNum, 33))    ' Columna AG
    
    If wbsValue <> "" And agValue <> "" Then
        sKey = agValue & "|" & wbsValue

        ' Contador por UUID
        If Not wbsDict.Exists(agValue) Then
            wbsDict.Add agValue, 1
            pepCounterDict.Add agValue, 0
        Else
            pepCounterDict(agValue) = pepCounterDict(agValue) + 1
            data(rowNum, 33) = agValue & " pep" & pepCounterDict(agValue)
            results(rowNum) = True ' Marcar para ocultar
        End If

        ' Duplicado exacto UUID + WBS
        If wbsDictH.Exists(sKey) Then
            results(rowNum) = True ' Marcar para ocultar
        Else
            wbsDictH.Add sKey, 1
        End If
    End If
Next

' Escribir los datos modificados de vuelta
objWorkbookSheetRef.Range("A2:AG" & lastRow).Value = data

' Ocultar filas en un solo paso
For rowNum = 1 To totalRows
    If results(rowNum) = True Then
        objWorkbookSheetRef.Rows(rowNum + 1).Hidden = True ' +1 por offset a partir de fila 2
    End If
Next

' Guardar y cerrar el libro de refacturación
objWorkbookPathRef.Save
objWorkbookPathRef.Close
' Cerrar la aplicación de Excel
objExcel.Quit

'Devuelve el error en caso de
If Err.Number <> 0 Then
    ' Cerrar la aplicación de Excel
    objExcel.Quit
    Msg = "Error was generated by " & Err.Source & ". " & Err.Description
    WScript.StdOut.WriteLine Msg
Else
    WScript.StdOut.WriteLine "Script executed successfully."
End if
